site_name: naacl2024_cove
nav:
  - Home: index.md

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      project_name: naacl2024_cove
      handlers:
        python:
          options:
            docstring_style: numpy